{% set name = "openimageio" %}
{% set version = "2.0.12" %}
{% set sha256 = "930a142c9cabbbc3b249577083c97e9f0407cc8cbf933144f3a3ed0f3ec9cfe0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Release-{{ version }}.tar.gz
  url: https://github.com/OpenImageIO/oiio/archive/Release-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - boost 1.70.0
    - ffmpeg 4.2
    - giflib
    - jpeg
    - libpng 1.6
    - libtiff 4.1
    - libwebp
    - openexr
  run:
    # boost and libwebp don't have a run_exports section
    - {{ pin_compatible('boost', max_pin='x.x.x') }}
    - {{ pin_compatible('libwebp', max_pin='x.x') }}
    # ffmpeg 3.x does not have a run-export section
    - {{ pin_compatible('ffmpeg', max_pin='x.x') }}

test:
  commands:
    - test -d ${PREFIX}/include/OpenImageIO  # [unix]
    - test -f ${PREFIX}/include/OpenImageIO/oiioversion.h  # [unix]
    - test -f ${PREFIX}/lib/libOpenImageIO.so  # [linux]
    - test -f ${PREFIX}/lib/libOpenImageIO.dylib  # [osx]

about:
  home: https://sites.google.com/site/openimageio/home
  license: BSD-3-Clause
  license_family: BSD
  summary: Simple but powerful APIs for reading & writing many image formats
  description: |
    OpenImageIO consists of:
    - Simple but powerful ImageInput and ImageOutput APIs that provide an abstraction
      for reading and writing image files of nearly any format, without the calling
      application needing to know any of the details of these file formats, and indeed
      without the calling application needing to be aware of which formats are available.
    - Plugins implementing I/O for several popular image file formats, including TIFF,
      JPEG/JFIF, OpenEXR, PNG, HDR/RGBE, ICO, BMP, Targa, JPEG-2000, RMan Zfile, FITS, DDS,
      Softimage PIC, PNM, DPX, Cineon, IFF, Field3D, Ptex, Photoshop PSD, Wavefront RLA, SGI,
      WebP, GIF, DICOM, many \"RAW\" digital camera formats, and a variety of movie formats
      (readable as individual frames). More are being developed all the time.
    - An ImageCache class that transparently manages a cache so that it can access truly
      vast amounts of image data (tens of thousands of image files totaling multiple TB)
      very efficiently using only a tiny amount (tens of megabytes at most) of runtime memory.

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
